
-- Temporarily disable RLS for testing (REMOVE THIS IN PRODUCTION!)
ALTER TABLE hospitals DISABLE ROW LEVEL SECURITY;
ALTER TABLE patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE patient_checkins DISABLE ROW LEVEL SECURITY;
ALTER TABLE hospital_beds DISABLE ROW LEVEL SECURITY;
ALTER TABLE hospital_wards DISABLE ROW LEVEL SECURITY;
ALTER TABLE hospital_billing DISABLE ROW LEVEL SECURITY;
ALTER TABLE hospital_notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE pharmacy_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE emr_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE lab_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE doctors DISABLE ROW LEVEL SECURITY;
ALTER TABLE hospital_doctors DISABLE ROW LEVEL SECURITY;
