// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's HealingNet profile. Detects whether the user is a patient, doctor, or hospital staff member and returns the matching profile row.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [patientRes, doctorRes, staffRes] = await Promise.all([
      sb.from("patients").select("id, first_name, last_name, email, phone, gender, blood_group, genotype, city, state").eq("user_id", userId).maybeSingle(),
      sb.rpc("get_user_doctor_id", { _user_id: userId }),
      sb.from("hospital_staff").select("hospital_id, role, is_active").eq("user_id", userId).eq("is_active", true).maybeSingle()
    ]);
    const profile = {
      user_id: userId,
      email: ctx.getUserEmail(),
      patient: patientRes.data ?? null,
      doctor_id: doctorRes.data ?? null,
      hospital_staff: staffRes.data ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-my-appointments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_appointments_default = defineTool2({
  name: "list_my_appointments",
  title: "List my appointments",
  description: "List the signed-in user's HealingNet appointments (as a patient or as an assigned doctor). Optionally filter by status.",
  inputSchema: {
    status: z.enum(["scheduled", "completed", "cancelled", "no_show", "in_progress"]).optional().describe("Optional appointment status filter."),
    limit: z.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let q = sb.from("patient_appointments").select("id, patient_id, hospital_id, doctor_id, requested_date, requested_time, reason, status, is_telemedicine, notes, created_at").order("requested_date", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-prescriptions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_prescriptions_default = defineTool3({
  name: "list_my_prescriptions",
  title: "List my prescriptions",
  description: "List the signed-in user's HealingNet prescriptions (as a patient or as the prescribing doctor). Optionally filter by status.",
  inputSchema: {
    status: z2.string().optional().describe("Optional prescription status (e.g. active, completed, cancelled)."),
    limit: z2.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("prescriptions").select("id, patient_id, doctor_id, hospital_id, drug_name, dosage, frequency, duration, instructions, refills_allowed, refills_used, status, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { prescriptions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-lab-results.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_lab_results_default = defineTool4({
  name: "list_my_lab_results",
  title: "List my lab results",
  description: "List the signed-in user's HealingNet lab result orders (as a patient or as the ordering doctor).",
  inputSchema: {
    status: z3.string().optional().describe("Optional lab order status filter."),
    limit: z3.number().int().min(1).max(100).default(25)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    let q = sb.from("lab_results").select("id, patient_id, hospital_id, ordered_by, status, notes, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lab_orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cjjbfrckrfuaqyrkmbfn";
var mcp_default = defineMcp({
  name: "healingnet-mcp",
  title: "HealingNet",
  version: "0.1.0",
  instructions: "Tools for HealingNet \u2014 a Nigerian healthcare platform. Read the signed-in user's profile, appointments, prescriptions, and lab orders. All tools respect Row-Level Security and operate as the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_my_appointments_default, list_my_prescriptions_default, list_my_lab_results_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
